### ISSUE TITLE
[Bug]: Speaker Button not working

### ISSUE THREAD

**Issue by rhl-bthr** [sugarlabs/reversi-activity#3]
**Steps to reproduce:**
 - Open the activity. `speaker` should be set to `on` state 
 - Click on the `speaker` button.

**Expected Result:**
 - `speaker` should be set to `off` state

**Observed Result:**
 - No change

**Logs:**
> `ToolButton` object has no attribute `set_icon`

(Error generated during port of activity to sugar-toolkit3)

**Comment by quozl** [comment]
Please just say "Fixes #3" so that merging a pull request will close the issue.

**Comment by rhl-bthr** [comment]
Oh, will do. Thank you
