### ISSUE TITLE
White color has no effect on the Player 1 circles

### ISSUE THREAD

**Issue by srevinsaju** [sugarlabs/reversi-activity#6]
![image](https://user-images.githubusercontent.com/48695438/73096481-eea63100-3ef5-11ea-909c-d2eabb5504bd.png)

But on choosing white, it still appears yellow (the background color of yellow), 
![image](https://user-images.githubusercontent.com/48695438/73096500-f8c82f80-3ef5-11ea-9198-6ca66d11f3af.png)

_Originally posted by @srevinsaju in https://github.com/sugarlabs/reversi-activity/pull/5#issuecomment-578260797_

**Comment by ayushnawal** [comment]
@srevinsaju will try and update you
